version: "2"

services:
  infobot:
    build: .
    image: acrelle/rpi-infobot
    container_name: infobot
    restart: unless-stopped
    volumes:
      - ~/appdata/infobot/infobot_data/files:/home/infobot/infobot-code/files 
      - ~/appdata/infobot/infobot_data/log:/home/infobot/infobot-code/log
